//
// Generated by Bluespec Compiler, version 2025.07 (build 282e82e)
//
// On Fri Jun 19 09:36:06 PDT 2026
//
//
// Ports:
// Name                         I/O  size props
// inReady                        O     1
// outValid_div                   O     1
// outValid_sqrt                  O     1
// result                         O    38
// CLK                            I     1 clock
// RST_N                          I     1 reset
// req_inValid                    I     1
// req_sqrtOp                     I     1
// req_a                          I    33
// req_b                          I    33
// req_roundingMode               I     3 reg
// result_control                 I     1
//
// Combinational paths from inputs to outputs:
//   result_control -> result
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkDivSqrtRecF32(CLK,
		       RST_N,

		       inReady,

		       req_inValid,
		       req_sqrtOp,
		       req_a,
		       req_b,
		       req_roundingMode,

		       outValid_div,

		       outValid_sqrt,

		       result_control,
		       result);
  input  CLK;
  input  RST_N;

  // value method inReady
  output inReady;

  // action method req
  input  req_inValid;
  input  req_sqrtOp;
  input  [32 : 0] req_a;
  input  [32 : 0] req_b;
  input  [2 : 0] req_roundingMode;

  // value method outValid_div
  output outValid_div;

  // value method outValid_sqrt
  output outValid_sqrt;

  // value method result
  input  result_control;
  output [37 : 0] result;

  // signals for module outputs
  wire [37 : 0] result;
  wire inReady, outValid_div, outValid_sqrt;

  // register m_divSqrtRecFNToRaw_divSqrtRawFN_cycleNum
  reg [4 : 0] m_divSqrtRecFNToRaw_divSqrtRawFN_cycleNum;
  wire [4 : 0] m_divSqrtRecFNToRaw_divSqrtRawFN_cycleNum$D_IN;
  wire m_divSqrtRecFNToRaw_divSqrtRawFN_cycleNum$EN;

  // register m_divSqrtRecFNToRaw_divSqrtRawFN_fractB_Z
  reg [23 : 0] m_divSqrtRecFNToRaw_divSqrtRawFN_fractB_Z;
  wire [23 : 0] m_divSqrtRecFNToRaw_divSqrtRawFN_fractB_Z$D_IN;
  wire m_divSqrtRecFNToRaw_divSqrtRawFN_fractB_Z$EN;

  // register m_divSqrtRecFNToRaw_divSqrtRawFN_isInf_Z
  reg m_divSqrtRecFNToRaw_divSqrtRawFN_isInf_Z;
  wire m_divSqrtRecFNToRaw_divSqrtRawFN_isInf_Z$D_IN,
       m_divSqrtRecFNToRaw_divSqrtRawFN_isInf_Z$EN;

  // register m_divSqrtRecFNToRaw_divSqrtRawFN_isNaN_Z
  reg m_divSqrtRecFNToRaw_divSqrtRawFN_isNaN_Z;
  wire m_divSqrtRecFNToRaw_divSqrtRawFN_isNaN_Z$D_IN,
       m_divSqrtRecFNToRaw_divSqrtRawFN_isNaN_Z$EN;

  // register m_divSqrtRecFNToRaw_divSqrtRawFN_isZero_Z
  reg m_divSqrtRecFNToRaw_divSqrtRawFN_isZero_Z;
  wire m_divSqrtRecFNToRaw_divSqrtRawFN_isZero_Z$D_IN,
       m_divSqrtRecFNToRaw_divSqrtRawFN_isZero_Z$EN;

  // register m_divSqrtRecFNToRaw_divSqrtRawFN_majorExc_Z
  reg m_divSqrtRecFNToRaw_divSqrtRawFN_majorExc_Z;
  wire m_divSqrtRecFNToRaw_divSqrtRawFN_majorExc_Z$D_IN,
       m_divSqrtRecFNToRaw_divSqrtRawFN_majorExc_Z$EN;

  // register m_divSqrtRecFNToRaw_divSqrtRawFN_notZeroRem_Z
  reg m_divSqrtRecFNToRaw_divSqrtRawFN_notZeroRem_Z;
  wire m_divSqrtRecFNToRaw_divSqrtRawFN_notZeroRem_Z$D_IN,
       m_divSqrtRecFNToRaw_divSqrtRawFN_notZeroRem_Z$EN;

  // register m_divSqrtRecFNToRaw_divSqrtRawFN_rem_Z
  reg [25 : 0] m_divSqrtRecFNToRaw_divSqrtRawFN_rem_Z;
  wire [25 : 0] m_divSqrtRecFNToRaw_divSqrtRawFN_rem_Z$D_IN;
  wire m_divSqrtRecFNToRaw_divSqrtRawFN_rem_Z$EN;

  // register m_divSqrtRecFNToRaw_divSqrtRawFN_roundingMode_Z
  reg [2 : 0] m_divSqrtRecFNToRaw_divSqrtRawFN_roundingMode_Z;
  wire [2 : 0] m_divSqrtRecFNToRaw_divSqrtRawFN_roundingMode_Z$D_IN;
  wire m_divSqrtRecFNToRaw_divSqrtRawFN_roundingMode_Z$EN;

  // register m_divSqrtRecFNToRaw_divSqrtRawFN_sExp_Z
  reg [9 : 0] m_divSqrtRecFNToRaw_divSqrtRawFN_sExp_Z;
  wire [9 : 0] m_divSqrtRecFNToRaw_divSqrtRawFN_sExp_Z$D_IN;
  wire m_divSqrtRecFNToRaw_divSqrtRawFN_sExp_Z$EN;

  // register m_divSqrtRecFNToRaw_divSqrtRawFN_sigX_Z
  reg [25 : 0] m_divSqrtRecFNToRaw_divSqrtRawFN_sigX_Z;
  wire [25 : 0] m_divSqrtRecFNToRaw_divSqrtRawFN_sigX_Z$D_IN;
  wire m_divSqrtRecFNToRaw_divSqrtRawFN_sigX_Z$EN;

  // register m_divSqrtRecFNToRaw_divSqrtRawFN_sign_Z
  reg m_divSqrtRecFNToRaw_divSqrtRawFN_sign_Z;
  wire m_divSqrtRecFNToRaw_divSqrtRawFN_sign_Z$D_IN,
       m_divSqrtRecFNToRaw_divSqrtRawFN_sign_Z$EN;

  // register m_divSqrtRecFNToRaw_divSqrtRawFN_sqrtOp_Z
  reg m_divSqrtRecFNToRaw_divSqrtRawFN_sqrtOp_Z;
  wire m_divSqrtRecFNToRaw_divSqrtRawFN_sqrtOp_Z$D_IN,
       m_divSqrtRecFNToRaw_divSqrtRawFN_sqrtOp_Z$EN;

  // rule scheduling signals
  wire CAN_FIRE_req, WILL_FIRE_req;

  // remaining internal signals
  wire [511 : 0] INV_x714__q5, x__h2714;
  wire [32 : 0] x__h2337;
  wire [29 : 0] IF_trialRemAsUInt936_BIT_29_THEN_0_CONCAT_rem9_ETC__q4,
		trialRemAsUInt__h1936;
  wire [28 : 0] _0b0_CONCAT_rem926__q2;
  wire [27 : 0] _0b0_CONCAT_trialTerm933__q3,
		remTerm1__h1919,
		remTerm2__h1924,
		remTerm3__h1925,
		rem__h1926,
		x__h2012;
  wire [26 : 0] _1_SL_m_divSqrtRecFNToRaw_divSqrtRawFN_cycleNum__q1,
		_theResult____h2368,
		in__h2583,
		in__h3000,
		roundMask__h2491,
		roundPosMask__h2493,
		shiftedRoundMask__h2492,
		trialTermT1__h1927,
		trialTermT2__h1928,
		trialTermT3__h1929,
		trialTermT4__h1930,
		trialTermT5__h1931,
		trialTermT6__h1932,
		trialTerm__h1933,
		x__h2106,
		x__h2107,
		x__h2108,
		x__h2109,
		x__h2650;
  wire [25 : 0] IF_m_divSqrtRecFNToRaw_divSqrtRawFN_roundingMo_ETC___d268,
		IF_m_divSqrtRecFNToRaw_divSqrtRawFN_roundingMo_ETC___d358,
		_0_CONCAT_m_divSqrtRecFNToRaw_divSqrtRawFN_sigX_ETC___d259,
		_0_CONCAT_m_divSqrtRecFNToRaw_divSqrtRawFN_sigX_ETC___d267,
		bitMask__h1958,
		m_divSqrtRecFNToRaw_divSqrtRawFN_sigX_Z_AND_IN_ETC__q6,
		m_divSqrtRecFNToRaw_divSqrtRawFN_sigX_Z_OR_INV_ETC__q7,
		sigXTerm1__h2240,
		sigXTerm2__h2241,
		sigXTerm3__h2242,
		sigXTerm4__h2243,
		sigXTerm5__h2244,
		x__h2261,
		x__h2262,
		x__h2263,
		x__h3022,
		x__h3057,
		y__h3023,
		y__h3058;
  wire [24 : 0] INV_134078079299425970995740249982058461274793_ETC___d228,
		remTerm2_lo__h1923;
  wire [23 : 0] IF_req_sqrtOp_THEN_IF_req_a_BIT_23_4_THEN_4194_ETC___d131,
		x__h1661,
		x__h1860;
  wire [22 : 0] IF_m_divSqrtRecFNToRaw_divSqrtRawFN_isNaN_Z_10_ETC___d331,
		_theResult_____1_snd_fst__h3082,
		fractOut__h2394;
  wire [11 : 0] SEXT_SEXT_m_divSqrtRecFNToRaw_divSqrtRawFN_sEx_ETC___d271;
  wire [10 : 0] SEXT__0_CONCAT_req_a_BITS_31_TO_23_10_11_12_PL_ETC___d118,
		SEXT_m_divSqrtRecFNToRaw_divSqrtRawFN_sExp_Z_14___d215;
  wire [9 : 0] _0_CONCAT_req_a_BITS_31_TO_23__q10;
  wire [8 : 0] aSExpHalved__h1386,
	       expOut__h2393,
	       req_b_BIT_31_CONCAT_bExpNegLow66__q11,
	       x__h2465,
	       x__h2467,
	       x__h2469,
	       x__h2471,
	       x__h2473,
	       x__h2475,
	       x__h2477,
	       y__h2466,
	       y__h2468,
	       y__h2470,
	       y__h2472,
	       y__h2474,
	       y__h2476,
	       y__h2478,
	       y__h2480,
	       y__h2717;
  wire [7 : 0] bExpNegLow__h466;
  wire [4 : 0] SEXT_SEXT_m_divSqrtRecFNToRaw_divSqrtRawFN_sEx_ETC__q8,
	       nextCycleNumTerm1__h516,
	       nextCycleNumTerm2__h517,
	       nextCycleNumTerm3__h518,
	       nextCycleNumTerm4__h519,
	       x__h559,
	       x__h560;
  wire [3 : 0] satTopNibble__h470;
  wire [2 : 0] SEXT_m_divSqrtRecFNToRaw_divSqrtRawFN_sExp_Z_1_ETC__q9,
	       remTerm2_hi__h1921;
  wire [1 : 0] aSigBits_hi__h1920, in__h5703;
  wire IF_req_sqrtOp_THEN_NOT_req_a_BITS_31_TO_30_EQ__ETC___d52,
       NOT_SEXT_SEXT_m_divSqrtRecFNToRaw_divSqrtRawFN_ETC___d293,
       NOT_m_divSqrtRecFNToRaw_divSqrtRawFN_isNaN_Z_1_ETC___d285,
       NOT_m_divSqrtRecFNToRaw_divSqrtRawFN_isNaN_Z_1_ETC___d288,
       NOT_m_divSqrtRecFNToRaw_divSqrtRawFN_isNaN_Z_1_ETC___d304,
       NOT_m_divSqrtRecFNToRaw_divSqrtRawFN_isNaN_Z_1_ETC___d313,
       NOT_m_divSqrtRecFNToRaw_divSqrtRawFN_roundingM_ETC___d376,
       NOT_m_divSqrtRecFNToRaw_divSqrtRawFN_sigX_Z_4__ETC___d352,
       NOT_m_divSqrtRecFNToRaw_divSqrtRawFN_sigX_Z_4__ETC___d379,
       NOT_result_control_53_OR_IF_m_divSqrtRecFNToRa_ETC___d364,
       SEXT_SEXT_m_divSqrtRecFNToRaw_divSqrtRawFN_sEx_ETC___d274,
       m_divSqrtRecFNToRaw_divSqrtRawFN_cycleNum_ULE_1___d4,
       m_divSqrtRecFNToRaw_divSqrtRawFN_majorExc_Z_78_ETC___d314,
       m_divSqrtRecFNToRaw_divSqrtRawFN_roundingMode__ETC___d250;

  // value method inReady
  assign inReady = m_divSqrtRecFNToRaw_divSqrtRawFN_cycleNum <= 5'd1 ;

  // action method req
  assign CAN_FIRE_req = 1'd1 ;
  assign WILL_FIRE_req = 1'd1 ;

  // value method outValid_div
  assign outValid_div =
	     m_divSqrtRecFNToRaw_divSqrtRawFN_cycleNum == 5'd1 &&
	     !m_divSqrtRecFNToRaw_divSqrtRawFN_sqrtOp_Z ;

  // value method outValid_sqrt
  assign outValid_sqrt =
	     m_divSqrtRecFNToRaw_divSqrtRawFN_cycleNum == 5'd1 &&
	     m_divSqrtRecFNToRaw_divSqrtRawFN_sqrtOp_Z ;

  // value method result
  assign result =
	     { x__h2337,
	       m_divSqrtRecFNToRaw_divSqrtRawFN_majorExc_Z &&
	       m_divSqrtRecFNToRaw_divSqrtRawFN_isNaN_Z,
	       m_divSqrtRecFNToRaw_divSqrtRawFN_majorExc_Z &&
	       !m_divSqrtRecFNToRaw_divSqrtRawFN_isNaN_Z,
	       NOT_m_divSqrtRecFNToRaw_divSqrtRawFN_isNaN_Z_1_ETC___d285 &&
	       NOT_SEXT_SEXT_m_divSqrtRecFNToRaw_divSqrtRawFN_ETC___d293,
	       NOT_m_divSqrtRecFNToRaw_divSqrtRawFN_isNaN_Z_1_ETC___d285 &&
	       (SEXT_SEXT_m_divSqrtRecFNToRaw_divSqrtRawFN_sEx_ETC___d274 ||
		NOT_m_divSqrtRecFNToRaw_divSqrtRawFN_sigX_Z_4__ETC___d379),
	       NOT_m_divSqrtRecFNToRaw_divSqrtRawFN_isNaN_Z_1_ETC___d285 &&
	       NOT_SEXT_SEXT_m_divSqrtRecFNToRaw_divSqrtRawFN_ETC___d293 ||
	       NOT_m_divSqrtRecFNToRaw_divSqrtRawFN_isNaN_Z_1_ETC___d285 &&
	       (SEXT_SEXT_m_divSqrtRecFNToRaw_divSqrtRawFN_sEx_ETC___d274 ||
		in__h2583 != 27'd0 ||
		in__h3000 != 27'd0) } ;

  // register m_divSqrtRecFNToRaw_divSqrtRawFN_cycleNum
  assign m_divSqrtRecFNToRaw_divSqrtRawFN_cycleNum$D_IN =
	     x__h559 | nextCycleNumTerm4__h519 ;
  assign m_divSqrtRecFNToRaw_divSqrtRawFN_cycleNum$EN =
	     m_divSqrtRecFNToRaw_divSqrtRawFN_cycleNum != 5'd0 ||
	     m_divSqrtRecFNToRaw_divSqrtRawFN_cycleNum_ULE_1___d4 &&
	     req_inValid ;

  // register m_divSqrtRecFNToRaw_divSqrtRawFN_fractB_Z
  assign m_divSqrtRecFNToRaw_divSqrtRawFN_fractB_Z$D_IN =
	     (m_divSqrtRecFNToRaw_divSqrtRawFN_cycleNum_ULE_1___d4 &&
	      req_inValid) ?
	       IF_req_sqrtOp_THEN_IF_req_a_BIT_23_4_THEN_4194_ETC___d131 :
	       x__h1860 ;
  assign m_divSqrtRecFNToRaw_divSqrtRawFN_fractB_Z$EN =
	     m_divSqrtRecFNToRaw_divSqrtRawFN_cycleNum_ULE_1___d4 &&
	     req_inValid ||
	     !m_divSqrtRecFNToRaw_divSqrtRawFN_cycleNum_ULE_1___d4 &&
	     m_divSqrtRecFNToRaw_divSqrtRawFN_sqrtOp_Z ;

  // register m_divSqrtRecFNToRaw_divSqrtRawFN_isInf_Z
  assign m_divSqrtRecFNToRaw_divSqrtRawFN_isInf_Z$D_IN =
	     req_sqrtOp ?
	       req_a[31:30] == 2'b11 && ~req_a[29] :
	       req_a[31:30] == 2'b11 && ~req_a[29] || req_b[31:29] == 3'b0 ;
  assign m_divSqrtRecFNToRaw_divSqrtRawFN_isInf_Z$EN =
	     m_divSqrtRecFNToRaw_divSqrtRawFN_cycleNum_ULE_1___d4 &&
	     req_inValid ;

  // register m_divSqrtRecFNToRaw_divSqrtRawFN_isNaN_Z
  assign m_divSqrtRecFNToRaw_divSqrtRawFN_isNaN_Z$D_IN =
	     req_sqrtOp ?
	       req_a[31:30] == 2'b11 && req_a[29] ||
	       req_a[31:29] != 3'b0 && req_a[32] :
	       req_a[31:30] == 2'b11 && req_a[29] ||
	       req_b[31:30] == 2'b11 && req_b[29] ||
	       req_a[31:29] == 3'b0 && req_b[31:29] == 3'b0 ||
	       req_a[31:30] == 2'b11 && ~req_a[29] && req_b[31:30] == 2'b11 &&
	       ~req_b[29] ;
  assign m_divSqrtRecFNToRaw_divSqrtRawFN_isNaN_Z$EN =
	     m_divSqrtRecFNToRaw_divSqrtRawFN_cycleNum_ULE_1___d4 &&
	     req_inValid ;

  // register m_divSqrtRecFNToRaw_divSqrtRawFN_isZero_Z
  assign m_divSqrtRecFNToRaw_divSqrtRawFN_isZero_Z$D_IN =
	     req_sqrtOp ?
	       req_a[31:29] == 3'b0 :
	       req_a[31:29] == 3'b0 || req_b[31:30] == 2'b11 && ~req_b[29] ;
  assign m_divSqrtRecFNToRaw_divSqrtRawFN_isZero_Z$EN =
	     m_divSqrtRecFNToRaw_divSqrtRawFN_cycleNum_ULE_1___d4 &&
	     req_inValid ;

  // register m_divSqrtRecFNToRaw_divSqrtRawFN_majorExc_Z
  assign m_divSqrtRecFNToRaw_divSqrtRawFN_majorExc_Z$D_IN =
	     req_sqrtOp ?
	       req_a[31:30] == 2'b11 && req_a[29] && !req_a[22] ||
	       (req_a[31:30] != 2'b11 || !req_a[29]) &&
	       req_a[31:29] != 3'b0 &&
	       req_a[32] :
	       req_a[31:30] == 2'b11 && req_a[29] && !req_a[22] ||
	       req_b[31:30] == 2'b11 && req_b[29] && !req_b[22] ||
	       req_a[31:30] == 2'b11 && ~req_a[29] && req_b[31:30] == 2'b11 &&
	       ~req_b[29] ||
	       (req_a[31:30] != 2'b11 || !req_a[29]) &&
	       (req_a[31:30] != 2'b11 || !(~req_a[29])) &&
	       req_b[31:29] == 3'b0 ;
  assign m_divSqrtRecFNToRaw_divSqrtRawFN_majorExc_Z$EN =
	     m_divSqrtRecFNToRaw_divSqrtRawFN_cycleNum_ULE_1___d4 &&
	     req_inValid ;

  // register m_divSqrtRecFNToRaw_divSqrtRawFN_notZeroRem_Z
  assign m_divSqrtRecFNToRaw_divSqrtRawFN_notZeroRem_Z$D_IN =
	     (m_divSqrtRecFNToRaw_divSqrtRawFN_cycleNum_ULE_1___d4 ||
	      !trialRemAsUInt__h1936[29]) ?
	       trialRemAsUInt__h1936 != 30'd0 :
	       m_divSqrtRecFNToRaw_divSqrtRawFN_notZeroRem_Z ;
  assign m_divSqrtRecFNToRaw_divSqrtRawFN_notZeroRem_Z$EN =
	     req_inValid ||
	     !m_divSqrtRecFNToRaw_divSqrtRawFN_cycleNum_ULE_1___d4 ;

  // register m_divSqrtRecFNToRaw_divSqrtRawFN_rem_Z
  assign m_divSqrtRecFNToRaw_divSqrtRawFN_rem_Z$D_IN =
	     IF_trialRemAsUInt936_BIT_29_THEN_0_CONCAT_rem9_ETC__q4[25:0] ;
  assign m_divSqrtRecFNToRaw_divSqrtRawFN_rem_Z$EN =
	     req_inValid ||
	     !m_divSqrtRecFNToRaw_divSqrtRawFN_cycleNum_ULE_1___d4 ;

  // register m_divSqrtRecFNToRaw_divSqrtRawFN_roundingMode_Z
  assign m_divSqrtRecFNToRaw_divSqrtRawFN_roundingMode_Z$D_IN =
	     req_roundingMode ;
  assign m_divSqrtRecFNToRaw_divSqrtRawFN_roundingMode_Z$EN =
	     m_divSqrtRecFNToRaw_divSqrtRawFN_cycleNum_ULE_1___d4 &&
	     req_inValid ;

  // register m_divSqrtRecFNToRaw_divSqrtRawFN_sExp_Z
  assign m_divSqrtRecFNToRaw_divSqrtRawFN_sExp_Z$D_IN =
	     req_sqrtOp ?
	       { aSExpHalved__h1386[8], aSExpHalved__h1386 } + 10'd128 :
	       { satTopNibble__h470,
		 SEXT__0_CONCAT_req_a_BITS_31_TO_23_10_11_12_PL_ETC___d118[5:0] } ;
  assign m_divSqrtRecFNToRaw_divSqrtRawFN_sExp_Z$EN =
	     m_divSqrtRecFNToRaw_divSqrtRawFN_cycleNum_ULE_1___d4 &&
	     req_inValid ;

  // register m_divSqrtRecFNToRaw_divSqrtRawFN_sigX_Z
  assign m_divSqrtRecFNToRaw_divSqrtRawFN_sigX_Z$D_IN =
	     x__h2261 | sigXTerm5__h2244 ;
  assign m_divSqrtRecFNToRaw_divSqrtRawFN_sigX_Z$EN =
	     req_inValid ||
	     !m_divSqrtRecFNToRaw_divSqrtRawFN_cycleNum_ULE_1___d4 ;

  // register m_divSqrtRecFNToRaw_divSqrtRawFN_sign_Z
  assign m_divSqrtRecFNToRaw_divSqrtRawFN_sign_Z$D_IN =
	     req_a[32] != (!req_sqrtOp && req_b[32]) ;
  assign m_divSqrtRecFNToRaw_divSqrtRawFN_sign_Z$EN =
	     m_divSqrtRecFNToRaw_divSqrtRawFN_cycleNum_ULE_1___d4 &&
	     req_inValid ;

  // register m_divSqrtRecFNToRaw_divSqrtRawFN_sqrtOp_Z
  assign m_divSqrtRecFNToRaw_divSqrtRawFN_sqrtOp_Z$D_IN = req_sqrtOp ;
  assign m_divSqrtRecFNToRaw_divSqrtRawFN_sqrtOp_Z$EN =
	     m_divSqrtRecFNToRaw_divSqrtRawFN_cycleNum_ULE_1___d4 &&
	     req_inValid ;

  // remaining internal signals
  assign IF_m_divSqrtRecFNToRaw_divSqrtRawFN_isNaN_Z_10_ETC___d331 =
	     (m_divSqrtRecFNToRaw_divSqrtRawFN_isNaN_Z ||
	      m_divSqrtRecFNToRaw_divSqrtRawFN_isZero_Z ||
	      SEXT_SEXT_m_divSqrtRecFNToRaw_divSqrtRawFN_sEx_ETC___d274) ?
	       (m_divSqrtRecFNToRaw_divSqrtRawFN_isNaN_Z ?
		  23'd4194304 :
		  23'd0) :
	       _theResult_____1_snd_fst__h3082 ;
  assign IF_m_divSqrtRecFNToRaw_divSqrtRawFN_roundingMo_ETC___d268 =
	     ((m_divSqrtRecFNToRaw_divSqrtRawFN_roundingMode_Z == 3'd0 ||
	       m_divSqrtRecFNToRaw_divSqrtRawFN_roundingMode_Z == 3'd4) &&
	      in__h2583 != 27'd0 ||
	      m_divSqrtRecFNToRaw_divSqrtRawFN_roundingMode__ETC___d250) ?
	       _0_CONCAT_m_divSqrtRecFNToRaw_divSqrtRawFN_sigX_ETC___d259 :
	       _0_CONCAT_m_divSqrtRecFNToRaw_divSqrtRawFN_sigX_ETC___d267 ;
  assign IF_m_divSqrtRecFNToRaw_divSqrtRawFN_roundingMo_ETC___d358 =
	     ((m_divSqrtRecFNToRaw_divSqrtRawFN_roundingMode_Z == 3'd0 ||
	       m_divSqrtRecFNToRaw_divSqrtRawFN_roundingMode_Z == 3'd4) &&
	      in__h2583 != 27'd0 ||
	      m_divSqrtRecFNToRaw_divSqrtRawFN_roundingMode_Z == 3'd2 &&
	      m_divSqrtRecFNToRaw_divSqrtRawFN_sign_Z ||
	      m_divSqrtRecFNToRaw_divSqrtRawFN_roundingMode_Z == 3'd3 &&
	      !m_divSqrtRecFNToRaw_divSqrtRawFN_sign_Z) ?
	       _0_CONCAT_m_divSqrtRecFNToRaw_divSqrtRawFN_sigX_ETC___d259 :
	       _0_CONCAT_m_divSqrtRecFNToRaw_divSqrtRawFN_sigX_ETC___d267 ;
  assign IF_req_sqrtOp_THEN_IF_req_a_BIT_23_4_THEN_4194_ETC___d131 =
	     req_sqrtOp ? (req_a[23] ? 24'd4194304 : 24'd8388608) : x__h1661 ;
  assign IF_req_sqrtOp_THEN_NOT_req_a_BITS_31_TO_30_EQ__ETC___d52 =
	     req_sqrtOp ?
	       (req_a[31:30] != 2'b11 || !req_a[29]) &&
	       (req_a[31:30] != 2'b11 || !(~req_a[29])) &&
	       req_a[31:29] != 3'b0 &&
	       !req_a[32] :
	       (req_a[31:30] != 2'b11 || !req_a[29]) &&
	       (req_a[31:30] != 2'b11 || !(~req_a[29])) &&
	       req_a[31:29] != 3'b0 &&
	       (req_b[31:30] != 2'b11 || !req_b[29]) &&
	       (req_b[31:30] != 2'b11 || !(~req_b[29])) &&
	       req_b[31:29] != 3'b0 ;
  assign IF_trialRemAsUInt936_BIT_29_THEN_0_CONCAT_rem9_ETC__q4 =
	     trialRemAsUInt__h1936[29] ?
	       { 2'd0, rem__h1926 } :
	       trialRemAsUInt__h1936 ;
  assign INV_134078079299425970995740249982058461274793_ETC___d228 =
	     INV_x714__q5[405:381] |
	     { 24'd0, m_divSqrtRecFNToRaw_divSqrtRawFN_sigX_Z[25] } ;
  assign INV_x714__q5 = ~x__h2714 ;
  assign NOT_SEXT_SEXT_m_divSqrtRecFNToRaw_divSqrtRawFN_ETC___d293 =
	     ({ {7{SEXT_SEXT_m_divSqrtRecFNToRaw_divSqrtRawFN_sEx_ETC__q8[4]}},
		SEXT_SEXT_m_divSqrtRecFNToRaw_divSqrtRawFN_sEx_ETC__q8 } ^
	      12'h800) >=
	     12'd2051 ;
  assign NOT_m_divSqrtRecFNToRaw_divSqrtRawFN_isNaN_Z_1_ETC___d285 =
	     !m_divSqrtRecFNToRaw_divSqrtRawFN_isNaN_Z &&
	     !m_divSqrtRecFNToRaw_divSqrtRawFN_majorExc_Z &&
	     !m_divSqrtRecFNToRaw_divSqrtRawFN_isInf_Z &&
	     !m_divSqrtRecFNToRaw_divSqrtRawFN_isZero_Z ;
  assign NOT_m_divSqrtRecFNToRaw_divSqrtRawFN_isNaN_Z_1_ETC___d288 =
	     NOT_m_divSqrtRecFNToRaw_divSqrtRawFN_isNaN_Z_1_ETC___d285 &&
	     SEXT_SEXT_m_divSqrtRecFNToRaw_divSqrtRawFN_sEx_ETC___d274 &&
	     (m_divSqrtRecFNToRaw_divSqrtRawFN_roundingMode_Z == 3'd2 &&
	      m_divSqrtRecFNToRaw_divSqrtRawFN_sign_Z ||
	      m_divSqrtRecFNToRaw_divSqrtRawFN_roundingMode_Z == 3'd3 &&
	      !m_divSqrtRecFNToRaw_divSqrtRawFN_sign_Z ||
	      m_divSqrtRecFNToRaw_divSqrtRawFN_roundingMode_Z == 3'd6) ;
  assign NOT_m_divSqrtRecFNToRaw_divSqrtRawFN_isNaN_Z_1_ETC___d304 =
	     NOT_m_divSqrtRecFNToRaw_divSqrtRawFN_isNaN_Z_1_ETC___d285 &&
	     NOT_SEXT_SEXT_m_divSqrtRecFNToRaw_divSqrtRawFN_ETC___d293 &&
	     m_divSqrtRecFNToRaw_divSqrtRawFN_roundingMode_Z != 3'd0 &&
	     m_divSqrtRecFNToRaw_divSqrtRawFN_roundingMode_Z != 3'd4 &&
	     (m_divSqrtRecFNToRaw_divSqrtRawFN_roundingMode_Z != 3'd2 ||
	      !m_divSqrtRecFNToRaw_divSqrtRawFN_sign_Z) &&
	     (m_divSqrtRecFNToRaw_divSqrtRawFN_roundingMode_Z != 3'd3 ||
	      m_divSqrtRecFNToRaw_divSqrtRawFN_sign_Z) ;
  assign NOT_m_divSqrtRecFNToRaw_divSqrtRawFN_isNaN_Z_1_ETC___d313 =
	     !m_divSqrtRecFNToRaw_divSqrtRawFN_isNaN_Z &&
	     !m_divSqrtRecFNToRaw_divSqrtRawFN_majorExc_Z &&
	     !m_divSqrtRecFNToRaw_divSqrtRawFN_isZero_Z &&
	     NOT_SEXT_SEXT_m_divSqrtRecFNToRaw_divSqrtRawFN_ETC___d293 &&
	     (m_divSqrtRecFNToRaw_divSqrtRawFN_roundingMode_Z == 3'd0 ||
	      m_divSqrtRecFNToRaw_divSqrtRawFN_roundingMode_Z == 3'd4 ||
	      m_divSqrtRecFNToRaw_divSqrtRawFN_roundingMode_Z == 3'd2 &&
	      m_divSqrtRecFNToRaw_divSqrtRawFN_sign_Z ||
	      m_divSqrtRecFNToRaw_divSqrtRawFN_roundingMode_Z == 3'd3 &&
	      !m_divSqrtRecFNToRaw_divSqrtRawFN_sign_Z) ;
  assign NOT_m_divSqrtRecFNToRaw_divSqrtRawFN_roundingM_ETC___d376 =
	     (m_divSqrtRecFNToRaw_divSqrtRawFN_roundingMode_Z != 3'd2 ||
	      !m_divSqrtRecFNToRaw_divSqrtRawFN_sign_Z) &&
	     (m_divSqrtRecFNToRaw_divSqrtRawFN_roundingMode_Z != 3'd3 ||
	      m_divSqrtRecFNToRaw_divSqrtRawFN_sign_Z) ||
	     (!m_divSqrtRecFNToRaw_divSqrtRawFN_sigX_Z[25] ||
	      !m_divSqrtRecFNToRaw_divSqrtRawFN_sigX_Z[1]) &&
	     in__h5703 == 2'd0 ;
  assign NOT_m_divSqrtRecFNToRaw_divSqrtRawFN_sigX_Z_4__ETC___d352 =
	     (in__h2583 != 27'd0 || in__h3000 != 27'd0) &&
	     ({ {8{SEXT_m_divSqrtRecFNToRaw_divSqrtRawFN_sExp_Z_1_ETC__q9[2]}},
		SEXT_m_divSqrtRecFNToRaw_divSqrtRawFN_sExp_Z_1_ETC__q9 } ^
	      11'h400) <=
	     11'd1024 &&
	     (m_divSqrtRecFNToRaw_divSqrtRawFN_sigX_Z[25] ?
		INV_134078079299425970995740249982058461274793_ETC___d228[1] :
		INV_134078079299425970995740249982058461274793_ETC___d228[0]) ;
  assign NOT_m_divSqrtRecFNToRaw_divSqrtRawFN_sigX_Z_4__ETC___d379 =
	     NOT_m_divSqrtRecFNToRaw_divSqrtRawFN_sigX_Z_4__ETC___d352 &&
	     (NOT_result_control_53_OR_IF_m_divSqrtRecFNToRa_ETC___d364 ||
	      in__h2583 == 27'd0 ||
	      (m_divSqrtRecFNToRaw_divSqrtRawFN_roundingMode_Z != 3'd0 &&
	       m_divSqrtRecFNToRaw_divSqrtRawFN_roundingMode_Z != 3'd4 ||
	       (m_divSqrtRecFNToRaw_divSqrtRawFN_sigX_Z[25] ?
		  !m_divSqrtRecFNToRaw_divSqrtRawFN_sigX_Z[1] :
		  !m_divSqrtRecFNToRaw_divSqrtRawFN_sigX_Z[0])) &&
	      NOT_m_divSqrtRecFNToRaw_divSqrtRawFN_roundingM_ETC___d376) ;
  assign NOT_result_control_53_OR_IF_m_divSqrtRecFNToRa_ETC___d364 =
	     !result_control ||
	     (m_divSqrtRecFNToRaw_divSqrtRawFN_sigX_Z[25] ?
		INV_134078079299425970995740249982058461274793_ETC___d228[2] ||
		!IF_m_divSqrtRecFNToRaw_divSqrtRawFN_roundingMo_ETC___d358[25] :
		INV_134078079299425970995740249982058461274793_ETC___d228[1] ||
		!IF_m_divSqrtRecFNToRaw_divSqrtRawFN_roundingMo_ETC___d358[24]) ;
  assign SEXT_SEXT_m_divSqrtRecFNToRaw_divSqrtRawFN_sEx_ETC___d271 =
	     { SEXT_m_divSqrtRecFNToRaw_divSqrtRawFN_sExp_Z_14___d215[10],
	       SEXT_m_divSqrtRecFNToRaw_divSqrtRawFN_sExp_Z_14___d215 } +
	     { 10'd0,
	       IF_m_divSqrtRecFNToRaw_divSqrtRawFN_roundingMo_ETC___d268[25:24] } ;
  assign SEXT_SEXT_m_divSqrtRecFNToRaw_divSqrtRawFN_sEx_ETC___d274 =
	     (SEXT_SEXT_m_divSqrtRecFNToRaw_divSqrtRawFN_sEx_ETC___d271 ^
	      12'h800) <
	     12'd2155 ;
  assign SEXT_SEXT_m_divSqrtRecFNToRaw_divSqrtRawFN_sEx_ETC__q8 =
	     SEXT_SEXT_m_divSqrtRecFNToRaw_divSqrtRawFN_sEx_ETC___d271[11:7] ;
  assign SEXT__0_CONCAT_req_a_BITS_31_TO_23_10_11_12_PL_ETC___d118 =
	     { _0_CONCAT_req_a_BITS_31_TO_23__q10[9],
	       _0_CONCAT_req_a_BITS_31_TO_23__q10 } +
	     { {2{req_b_BIT_31_CONCAT_bExpNegLow66__q11[8]}},
	       req_b_BIT_31_CONCAT_bExpNegLow66__q11 } ;
  assign SEXT_m_divSqrtRecFNToRaw_divSqrtRawFN_sExp_Z_14___d215 =
	     { m_divSqrtRecFNToRaw_divSqrtRawFN_sExp_Z[9],
	       m_divSqrtRecFNToRaw_divSqrtRawFN_sExp_Z } ;
  assign SEXT_m_divSqrtRecFNToRaw_divSqrtRawFN_sExp_Z_1_ETC__q9 =
	     SEXT_m_divSqrtRecFNToRaw_divSqrtRawFN_sExp_Z_14___d215[10:8] ;
  assign _0_CONCAT_m_divSqrtRecFNToRaw_divSqrtRawFN_sigX_ETC___d259 =
	     x__h3022 & y__h3023 ;
  assign _0_CONCAT_m_divSqrtRecFNToRaw_divSqrtRawFN_sigX_ETC___d267 =
	     x__h3057 | y__h3058 ;
  assign _0_CONCAT_req_a_BITS_31_TO_23__q10 = { 1'd0, req_a[31:23] } ;
  assign _0b0_CONCAT_rem926__q2 = { 1'b0, rem__h1926 } ;
  assign _0b0_CONCAT_trialTerm933__q3 = { 1'b0, trialTerm__h1933 } ;
  assign _1_SL_m_divSqrtRecFNToRaw_divSqrtRawFN_cycleNum__q1 =
	     27'd1 << m_divSqrtRecFNToRaw_divSqrtRawFN_cycleNum ;
  assign _theResult_____1_snd_fst__h3082 =
	     m_divSqrtRecFNToRaw_divSqrtRawFN_sigX_Z[25] ?
	       IF_m_divSqrtRecFNToRaw_divSqrtRawFN_roundingMo_ETC___d268[23:1] :
	       IF_m_divSqrtRecFNToRaw_divSqrtRawFN_roundingMo_ETC___d268[22:0] ;
  assign _theResult____h2368 =
	     { m_divSqrtRecFNToRaw_divSqrtRawFN_sigX_Z,
	       m_divSqrtRecFNToRaw_divSqrtRawFN_notZeroRem_Z } ;
  assign aSExpHalved__h1386 = { 1'd0, req_a[31:24] } ;
  assign aSigBits_hi__h1920 = { req_a[31:29] != 3'b0, req_a[22] } ;
  assign bExpNegLow__h466 = ~req_b[30:23] ;
  assign bitMask__h1958 =
	     { 1'd0,
	       _1_SL_m_divSqrtRecFNToRaw_divSqrtRawFN_cycleNum__q1[26:2] } ;
  assign expOut__h2393 = x__h2465 | y__h2466 ;
  assign fractOut__h2394 =
	     IF_m_divSqrtRecFNToRaw_divSqrtRawFN_isNaN_Z_10_ETC___d331 |
	     {23{NOT_m_divSqrtRecFNToRaw_divSqrtRawFN_isNaN_Z_1_ETC___d304}} ;
  assign in__h2583 = _theResult____h2368 & roundPosMask__h2493 ;
  assign in__h3000 = _theResult____h2368 & shiftedRoundMask__h2492 ;
  assign in__h5703 =
	     { m_divSqrtRecFNToRaw_divSqrtRawFN_sigX_Z[0],
	       m_divSqrtRecFNToRaw_divSqrtRawFN_notZeroRem_Z } ;
  assign m_divSqrtRecFNToRaw_divSqrtRawFN_cycleNum_ULE_1___d4 =
	     m_divSqrtRecFNToRaw_divSqrtRawFN_cycleNum <= 5'd1 ;
  assign m_divSqrtRecFNToRaw_divSqrtRawFN_majorExc_Z_78_ETC___d314 =
	     m_divSqrtRecFNToRaw_divSqrtRawFN_majorExc_Z &&
	     !m_divSqrtRecFNToRaw_divSqrtRawFN_isNaN_Z ||
	     m_divSqrtRecFNToRaw_divSqrtRawFN_isInf_Z ||
	     NOT_m_divSqrtRecFNToRaw_divSqrtRawFN_isNaN_Z_1_ETC___d313 ;
  assign m_divSqrtRecFNToRaw_divSqrtRawFN_roundingMode__ETC___d250 =
	     (m_divSqrtRecFNToRaw_divSqrtRawFN_roundingMode_Z == 3'd2 &&
	      m_divSqrtRecFNToRaw_divSqrtRawFN_sign_Z ||
	      m_divSqrtRecFNToRaw_divSqrtRawFN_roundingMode_Z == 3'd3 &&
	      !m_divSqrtRecFNToRaw_divSqrtRawFN_sign_Z) &&
	     (in__h2583 != 27'd0 || in__h3000 != 27'd0) ;
  assign m_divSqrtRecFNToRaw_divSqrtRawFN_sigX_Z_AND_IN_ETC__q6 =
	     m_divSqrtRecFNToRaw_divSqrtRawFN_sigX_Z &
	     { ~INV_134078079299425970995740249982058461274793_ETC___d228,
	       1'd0 } ;
  assign m_divSqrtRecFNToRaw_divSqrtRawFN_sigX_Z_OR_INV_ETC__q7 =
	     m_divSqrtRecFNToRaw_divSqrtRawFN_sigX_Z |
	     { INV_134078079299425970995740249982058461274793_ETC___d228,
	       1'd1 } ;
  assign nextCycleNumTerm1__h516 =
	     (m_divSqrtRecFNToRaw_divSqrtRawFN_cycleNum_ULE_1___d4 &&
	      req_inValid &&
	      (req_sqrtOp ?
		 req_a[31:30] == 2'b11 || req_a[31:29] == 3'b0 || req_a[32] :
		 req_a[31:30] == 2'b11 || req_a[31:29] == 3'b0 ||
		 req_b[31:30] == 2'b11 ||
		 req_b[31:29] == 3'b0)) ?
	       5'd1 :
	       5'd0 ;
  assign nextCycleNumTerm2__h517 =
	     (m_divSqrtRecFNToRaw_divSqrtRawFN_cycleNum_ULE_1___d4 &&
	      req_inValid &&
	      IF_req_sqrtOp_THEN_NOT_req_a_BITS_31_TO_30_EQ__ETC___d52) ?
	       (req_sqrtOp ? (req_a[23] ? 5'd24 : 5'd25) : 5'd26) :
	       5'd0 ;
  assign nextCycleNumTerm3__h518 =
	     ((!m_divSqrtRecFNToRaw_divSqrtRawFN_cycleNum_ULE_1___d4 ||
	       !req_inValid) &&
	      (m_divSqrtRecFNToRaw_divSqrtRawFN_cycleNum != 5'd3 ||
	       !m_divSqrtRecFNToRaw_divSqrtRawFN_sigX_Z[25])) ?
	       m_divSqrtRecFNToRaw_divSqrtRawFN_cycleNum - 5'd1 :
	       5'd0 ;
  assign nextCycleNumTerm4__h519 =
	     (m_divSqrtRecFNToRaw_divSqrtRawFN_cycleNum == 5'd3 &&
	      m_divSqrtRecFNToRaw_divSqrtRawFN_sigX_Z[25]) ?
	       5'd1 :
	       5'd0 ;
  assign remTerm1__h1919 =
	     (m_divSqrtRecFNToRaw_divSqrtRawFN_cycleNum_ULE_1___d4 &&
	      (!req_sqrtOp || !req_a[23])) ?
	       { 3'd0, req_a[31:29] != 3'b0, req_a[22:0], 1'd0 } :
	       28'd0 ;
  assign remTerm2__h1924 =
	     (m_divSqrtRecFNToRaw_divSqrtRawFN_cycleNum_ULE_1___d4 &&
	      req_sqrtOp &&
	      req_a[23]) ?
	       { remTerm2_hi__h1921, remTerm2_lo__h1923 } :
	       28'd0 ;
  assign remTerm2_hi__h1921 = { 1'd0, aSigBits_hi__h1920 } - 3'd1 ;
  assign remTerm2_lo__h1923 = { req_a[21:0], 3'd0 } ;
  assign remTerm3__h1925 =
	     m_divSqrtRecFNToRaw_divSqrtRawFN_cycleNum_ULE_1___d4 ?
	       28'd0 :
	       { 1'd0, m_divSqrtRecFNToRaw_divSqrtRawFN_rem_Z, 1'd0 } ;
  assign rem__h1926 = x__h2012 | remTerm3__h1925 ;
  assign req_b_BIT_31_CONCAT_bExpNegLow66__q11 =
	     { req_b[31], bExpNegLow__h466 } ;
  assign roundMask__h2491 =
	     { INV_134078079299425970995740249982058461274793_ETC___d228,
	       2'b11 } ;
  assign roundPosMask__h2493 = x__h2650 & roundMask__h2491 ;
  assign satTopNibble__h470 =
	     ((SEXT__0_CONCAT_req_a_BITS_31_TO_23_10_11_12_PL_ETC___d118 ^
	       11'h400) <
	      11'd1472) ?
	       SEXT__0_CONCAT_req_a_BITS_31_TO_23_10_11_12_PL_ETC___d118[9:6] :
	       4'b0110 ;
  assign shiftedRoundMask__h2492 =
	     { 1'd0,
	       INV_134078079299425970995740249982058461274793_ETC___d228,
	       1'd1 } ;
  assign sigXTerm1__h2240 =
	     (m_divSqrtRecFNToRaw_divSqrtRawFN_cycleNum_ULE_1___d4 &&
	      !req_sqrtOp) ?
	       { !trialRemAsUInt__h1936[29], 25'd0 } :
	       26'd0 ;
  assign sigXTerm2__h2241 =
	     (m_divSqrtRecFNToRaw_divSqrtRawFN_cycleNum_ULE_1___d4 &&
	      req_sqrtOp) ?
	       26'd16777216 :
	       26'd0 ;
  assign sigXTerm3__h2242 =
	     (m_divSqrtRecFNToRaw_divSqrtRawFN_cycleNum_ULE_1___d4 &&
	      req_sqrtOp &&
	      req_a[23]) ?
	       { 2'd0, !trialRemAsUInt__h1936[29], 23'd0 } :
	       26'd0 ;
  assign sigXTerm4__h2243 =
	     m_divSqrtRecFNToRaw_divSqrtRawFN_cycleNum_ULE_1___d4 ?
	       26'd0 :
	       m_divSqrtRecFNToRaw_divSqrtRawFN_sigX_Z ;
  assign sigXTerm5__h2244 =
	     (!m_divSqrtRecFNToRaw_divSqrtRawFN_cycleNum_ULE_1___d4 &&
	      !trialRemAsUInt__h1936[29]) ?
	       bitMask__h1958 :
	       26'd0 ;
  assign trialRemAsUInt__h1936 =
	     { _0b0_CONCAT_rem926__q2[28], _0b0_CONCAT_rem926__q2 } -
	     { {2{_0b0_CONCAT_trialTerm933__q3[27]}},
	       _0b0_CONCAT_trialTerm933__q3 } ;
  assign trialTermT1__h1927 =
	     (m_divSqrtRecFNToRaw_divSqrtRawFN_cycleNum_ULE_1___d4 &&
	      !req_sqrtOp) ?
	       { 2'd0, req_b[31:29] != 3'b0, req_b[22:0], 1'd0 } :
	       27'd0 ;
  assign trialTermT2__h1928 =
	     (m_divSqrtRecFNToRaw_divSqrtRawFN_cycleNum_ULE_1___d4 &&
	      req_sqrtOp &&
	      !req_a[23]) ?
	       27'd16777216 :
	       27'd0 ;
  assign trialTermT3__h1929 =
	     (m_divSqrtRecFNToRaw_divSqrtRawFN_cycleNum_ULE_1___d4 &&
	      req_sqrtOp &&
	      req_a[23]) ?
	       27'd41943040 :
	       27'd0 ;
  assign trialTermT4__h1930 =
	     m_divSqrtRecFNToRaw_divSqrtRawFN_cycleNum_ULE_1___d4 ?
	       27'd0 :
	       { 3'd0, m_divSqrtRecFNToRaw_divSqrtRawFN_fractB_Z } ;
  assign trialTermT5__h1931 =
	     (!m_divSqrtRecFNToRaw_divSqrtRawFN_cycleNum_ULE_1___d4 &&
	      !m_divSqrtRecFNToRaw_divSqrtRawFN_sqrtOp_Z) ?
	       27'd16777216 :
	       27'd0 ;
  assign trialTermT6__h1932 =
	     (!m_divSqrtRecFNToRaw_divSqrtRawFN_cycleNum_ULE_1___d4 &&
	      m_divSqrtRecFNToRaw_divSqrtRawFN_sqrtOp_Z) ?
	       { m_divSqrtRecFNToRaw_divSqrtRawFN_sigX_Z, 1'd0 } :
	       27'd0 ;
  assign trialTerm__h1933 = x__h2106 | trialTermT6__h1932 ;
  assign x__h1661 = { req_b[22:0], 1'b0 } ;
  assign x__h1860 =
	     { 1'd0, m_divSqrtRecFNToRaw_divSqrtRawFN_fractB_Z[23:1] } ;
  assign x__h2012 = remTerm1__h1919 | remTerm2__h1924 ;
  assign x__h2106 = x__h2107 | trialTermT5__h1931 ;
  assign x__h2107 = x__h2108 | trialTermT4__h1930 ;
  assign x__h2108 = x__h2109 | trialTermT3__h1929 ;
  assign x__h2109 = trialTermT1__h1927 | trialTermT2__h1928 ;
  assign x__h2261 = x__h2262 | sigXTerm4__h2243 ;
  assign x__h2262 = x__h2263 | sigXTerm3__h2242 ;
  assign x__h2263 = sigXTerm1__h2240 | sigXTerm2__h2241 ;
  assign x__h2337 =
	     { !m_divSqrtRecFNToRaw_divSqrtRawFN_isNaN_Z &&
	       m_divSqrtRecFNToRaw_divSqrtRawFN_sign_Z,
	       expOut__h2393,
	       fractOut__h2394 } ;
  assign x__h2465 = x__h2467 | y__h2468 ;
  assign x__h2467 = x__h2469 | y__h2470 ;
  assign x__h2469 = x__h2471 | y__h2472 ;
  assign x__h2471 = x__h2473 & y__h2474 ;
  assign x__h2473 = x__h2475 & y__h2476 ;
  assign x__h2475 = x__h2477 & y__h2478 ;
  assign x__h2477 =
	     SEXT_SEXT_m_divSqrtRecFNToRaw_divSqrtRawFN_sEx_ETC___d271[8:0] &
	     y__h2480 ;
  assign x__h2650 =
	     { 1'd1,
	       ~INV_134078079299425970995740249982058461274793_ETC___d228,
	       1'd0 } ;
  assign x__h2714 =
	     512'hFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF <<
	     y__h2717 ;
  assign x__h3022 =
	     { 1'd0,
	       m_divSqrtRecFNToRaw_divSqrtRawFN_sigX_Z_OR_INV_ETC__q7[25:1] } +
	     26'd1 ;
  assign x__h3057 =
	     { 1'd0,
	       m_divSqrtRecFNToRaw_divSqrtRawFN_sigX_Z_AND_IN_ETC__q6[25:1] } ;
  assign x__h559 = x__h560 | nextCycleNumTerm3__h518 ;
  assign x__h560 = nextCycleNumTerm1__h516 | nextCycleNumTerm2__h517 ;
  assign y__h2466 = m_divSqrtRecFNToRaw_divSqrtRawFN_isNaN_Z ? 9'd448 : 9'd0 ;
  assign y__h2468 =
	     m_divSqrtRecFNToRaw_divSqrtRawFN_majorExc_Z_78_ETC___d314 ?
	       9'd384 :
	       9'd0 ;
  assign y__h2470 =
	     NOT_m_divSqrtRecFNToRaw_divSqrtRawFN_isNaN_Z_1_ETC___d304 ?
	       9'd383 :
	       9'd0 ;
  assign y__h2472 =
	     NOT_m_divSqrtRecFNToRaw_divSqrtRawFN_isNaN_Z_1_ETC___d288 ?
	       9'd107 :
	       9'd0 ;
  assign y__h2474 =
	     m_divSqrtRecFNToRaw_divSqrtRawFN_majorExc_Z_78_ETC___d314 ?
	       9'd447 :
	       9'd511 ;
  assign y__h2476 =
	     NOT_m_divSqrtRecFNToRaw_divSqrtRawFN_isNaN_Z_1_ETC___d304 ?
	       9'd383 :
	       9'd511 ;
  assign y__h2478 =
	     NOT_m_divSqrtRecFNToRaw_divSqrtRawFN_isNaN_Z_1_ETC___d288 ?
	       9'd107 :
	       9'd511 ;
  assign y__h2480 =
	     (m_divSqrtRecFNToRaw_divSqrtRawFN_isZero_Z ||
	      SEXT_SEXT_m_divSqrtRecFNToRaw_divSqrtRawFN_sEx_ETC___d274) ?
	       9'd63 :
	       9'd511 ;
  assign y__h2717 =
	     ~SEXT_m_divSqrtRecFNToRaw_divSqrtRawFN_sExp_Z_14___d215[8:0] ;
  assign y__h3023 =
	     (m_divSqrtRecFNToRaw_divSqrtRawFN_roundingMode_Z == 3'd0 &&
	      in__h2583 != 27'd0 &&
	      in__h3000 == 27'd0) ?
	       { ~INV_134078079299425970995740249982058461274793_ETC___d228,
		 1'd0 } :
	       26'd67108863 ;
  assign y__h3058 =
	     (m_divSqrtRecFNToRaw_divSqrtRawFN_roundingMode_Z == 3'd6 &&
	      (in__h2583 != 27'd0 || in__h3000 != 27'd0)) ?
	       roundPosMask__h2493[26:1] :
	       26'd0 ;

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        m_divSqrtRecFNToRaw_divSqrtRawFN_cycleNum <= `BSV_ASSIGNMENT_DELAY
	    5'd0;
      end
    else
      begin
        if (m_divSqrtRecFNToRaw_divSqrtRawFN_cycleNum$EN)
	  m_divSqrtRecFNToRaw_divSqrtRawFN_cycleNum <= `BSV_ASSIGNMENT_DELAY
	      m_divSqrtRecFNToRaw_divSqrtRawFN_cycleNum$D_IN;
      end
    if (m_divSqrtRecFNToRaw_divSqrtRawFN_fractB_Z$EN)
      m_divSqrtRecFNToRaw_divSqrtRawFN_fractB_Z <= `BSV_ASSIGNMENT_DELAY
	  m_divSqrtRecFNToRaw_divSqrtRawFN_fractB_Z$D_IN;
    if (m_divSqrtRecFNToRaw_divSqrtRawFN_isInf_Z$EN)
      m_divSqrtRecFNToRaw_divSqrtRawFN_isInf_Z <= `BSV_ASSIGNMENT_DELAY
	  m_divSqrtRecFNToRaw_divSqrtRawFN_isInf_Z$D_IN;
    if (m_divSqrtRecFNToRaw_divSqrtRawFN_isNaN_Z$EN)
      m_divSqrtRecFNToRaw_divSqrtRawFN_isNaN_Z <= `BSV_ASSIGNMENT_DELAY
	  m_divSqrtRecFNToRaw_divSqrtRawFN_isNaN_Z$D_IN;
    if (m_divSqrtRecFNToRaw_divSqrtRawFN_isZero_Z$EN)
      m_divSqrtRecFNToRaw_divSqrtRawFN_isZero_Z <= `BSV_ASSIGNMENT_DELAY
	  m_divSqrtRecFNToRaw_divSqrtRawFN_isZero_Z$D_IN;
    if (m_divSqrtRecFNToRaw_divSqrtRawFN_majorExc_Z$EN)
      m_divSqrtRecFNToRaw_divSqrtRawFN_majorExc_Z <= `BSV_ASSIGNMENT_DELAY
	  m_divSqrtRecFNToRaw_divSqrtRawFN_majorExc_Z$D_IN;
    if (m_divSqrtRecFNToRaw_divSqrtRawFN_notZeroRem_Z$EN)
      m_divSqrtRecFNToRaw_divSqrtRawFN_notZeroRem_Z <= `BSV_ASSIGNMENT_DELAY
	  m_divSqrtRecFNToRaw_divSqrtRawFN_notZeroRem_Z$D_IN;
    if (m_divSqrtRecFNToRaw_divSqrtRawFN_rem_Z$EN)
      m_divSqrtRecFNToRaw_divSqrtRawFN_rem_Z <= `BSV_ASSIGNMENT_DELAY
	  m_divSqrtRecFNToRaw_divSqrtRawFN_rem_Z$D_IN;
    if (m_divSqrtRecFNToRaw_divSqrtRawFN_roundingMode_Z$EN)
      m_divSqrtRecFNToRaw_divSqrtRawFN_roundingMode_Z <= `BSV_ASSIGNMENT_DELAY
	  m_divSqrtRecFNToRaw_divSqrtRawFN_roundingMode_Z$D_IN;
    if (m_divSqrtRecFNToRaw_divSqrtRawFN_sExp_Z$EN)
      m_divSqrtRecFNToRaw_divSqrtRawFN_sExp_Z <= `BSV_ASSIGNMENT_DELAY
	  m_divSqrtRecFNToRaw_divSqrtRawFN_sExp_Z$D_IN;
    if (m_divSqrtRecFNToRaw_divSqrtRawFN_sigX_Z$EN)
      m_divSqrtRecFNToRaw_divSqrtRawFN_sigX_Z <= `BSV_ASSIGNMENT_DELAY
	  m_divSqrtRecFNToRaw_divSqrtRawFN_sigX_Z$D_IN;
    if (m_divSqrtRecFNToRaw_divSqrtRawFN_sign_Z$EN)
      m_divSqrtRecFNToRaw_divSqrtRawFN_sign_Z <= `BSV_ASSIGNMENT_DELAY
	  m_divSqrtRecFNToRaw_divSqrtRawFN_sign_Z$D_IN;
    if (m_divSqrtRecFNToRaw_divSqrtRawFN_sqrtOp_Z$EN)
      m_divSqrtRecFNToRaw_divSqrtRawFN_sqrtOp_Z <= `BSV_ASSIGNMENT_DELAY
	  m_divSqrtRecFNToRaw_divSqrtRawFN_sqrtOp_Z$D_IN;
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    m_divSqrtRecFNToRaw_divSqrtRawFN_cycleNum = 5'h0A;
    m_divSqrtRecFNToRaw_divSqrtRawFN_fractB_Z = 24'hAAAAAA;
    m_divSqrtRecFNToRaw_divSqrtRawFN_isInf_Z = 1'h0;
    m_divSqrtRecFNToRaw_divSqrtRawFN_isNaN_Z = 1'h0;
    m_divSqrtRecFNToRaw_divSqrtRawFN_isZero_Z = 1'h0;
    m_divSqrtRecFNToRaw_divSqrtRawFN_majorExc_Z = 1'h0;
    m_divSqrtRecFNToRaw_divSqrtRawFN_notZeroRem_Z = 1'h0;
    m_divSqrtRecFNToRaw_divSqrtRawFN_rem_Z = 26'h2AAAAAA;
    m_divSqrtRecFNToRaw_divSqrtRawFN_roundingMode_Z = 3'h2;
    m_divSqrtRecFNToRaw_divSqrtRawFN_sExp_Z = 10'h2AA;
    m_divSqrtRecFNToRaw_divSqrtRawFN_sigX_Z = 26'h2AAAAAA;
    m_divSqrtRecFNToRaw_divSqrtRawFN_sign_Z = 1'h0;
    m_divSqrtRecFNToRaw_divSqrtRawFN_sqrtOp_Z = 1'h0;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on
endmodule  // mkDivSqrtRecF32

